// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hmmibd_c
int hmmibd_c(Rcpp::List param_list);
RcppExport SEXP _hmmibdr_hmmibd_c(SEXP param_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type param_list(param_listSEXP);
    rcpp_result_gen = Rcpp::wrap(hmmibd_c(param_list));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hmmibdr_hmmibd_c", (DL_FUNC) &_hmmibdr_hmmibd_c, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_hmmibdr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
