# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' hmmIBD
#' @description
#' hmmIBD implementation from https://github.com/glipsnort/hmmIBD
#'
#' @param param_list A list of parameters created with \code{hmm_ibd}
#'
#' @details
#' \code{hmmibd_c} implements hidden Markov model for detecting segments
#'   of shared ancestry (identity by descent) in genetic sequence data.
#'
#' @export
hmmibd_c <- function(param_list) {
    .Call('_hmmibdr_hmmibd_c', PACKAGE = 'hmmibdr', param_list)
}

